# This file specifies rules for correctness according to how frappe doctype data model works.

rules:
- id: frappe-modifying-after-submit
  patterns:
    - pattern: self.$ATTR = ...
    - pattern-inside: |
        def on_submit(self, ...):
          ...
  message: |
    Doctype modified after submission. Plesae check if modification of self.$ATTR is commited to database.
  languages: [python]
  severity: ERROR
