name: Linters

on:
  pull_request: { }

  push:
      branches: ["develop"]

jobs:
  semgrep:
    name: Semgrep rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        env:
            SEMGREP_TIMEOUT: 300
        with:
            config: .github/helper/semgrep_rules

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Flake8
        run: pip install -q flake8 && flake8 ${GITHUB_WORKSPACE}
